import Head from 'next/head'
import SideNav from '../components/common/SideNav'
import MainApp from '../components/common/MainApp'

export default function Home() {
  return (
    <>
      <Head>
        <title>Spotify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SideNav />
      <MainApp>
        
      </MainApp>
    </>
  )
}
