import Head from 'next/head'
import MainApp from '../components/layouts/MainApp'
import RectangularCard from '../components/common/RectangularCard'
import SquareCard from '../components/common/SquareCard'
import styles from '../styles/pages/index.module.scss'

export default function Home() {
  return (
    <>
      <Head>
        <title>Spotify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainApp>
        <h1>Buenas noches</h1>
        <div className={styles["recently-listen-section"]}>
          <RectangularCard />
          <RectangularCard />
          <RectangularCard />
          <RectangularCard />
          <RectangularCard />
          <RectangularCard />
          <h2>Episodios para ti</h2>
        </div>
        <div className={styles["square-cards-section"]}>
          <SquareCard />
          <SquareCard />
          <SquareCard />
          <SquareCard />
          <SquareCard />
          <SquareCard />
          <SquareCard />
          <SquareCard />
          <SquareCard />
          <SquareCard />
          <SquareCard />
          <SquareCard />
          <SquareCard />
          <SquareCard />
          <SquareCard />
          <SquareCard />
        </div>
      </MainApp>
    </>
  )
}

