import Head from 'next/head'
import MainApp from '../components/layouts/MainApp'
import RectangularCard from '../components/common/RectangularCard'
import SquareCard from '../components/common/SquareCard'
import GenderCards from '../components/common/GenderCards'
import styles from '../styles/pages/index.module.scss'
import AlbumSongs from '../components/layouts/AlbumSongs'
import Player from '../components/common/Player'

export default function Home() {
  return (
    <>
      <Head>
        <title>Spotify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainApp>
        <AlbumSongs/>
      </MainApp>
      <Player/>
    </>
  )
}

