import Head from 'next/head'
import MainApp from '../components/layouts/MainApp'
import RectangularCard from '../components/common/RectangularCard'

export default function Home() {
  return (
    <>
      <Head>
        <title>Spotify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainApp>
        {/* <RectangularCard/> */}
      </MainApp>
    </>
  )
}

